# FLASK/GUNICORN PARAMETERS
port: 5005
bind_hosts: 127.0.0.1
workers: 12
threads: 4

# APPLICATION PARAMETERS
install_dir: /var/www/flask/kacky-eventpage-backend
cachetime: 60 # seconds
mapchangetime_s: 45
log_visits: 0 # 0, 1
visits_logfile: visits.log # might require absolute path
enable_stats_page: False # Turning this on provides a DDOS attack vector
enable_discord_bot: True

# META INFO
compend: 17.09.2023 22:00
eventtype: KR # [KK, KR, KX]
edition: 4 # edition of the eventtype
# playlist parameter can have values ["linear", "custom"]
# - "linear" for [min_mapid, ... max_mapid] on every server
# - "custom" for different maps per server (e. g. colors/difficulties)
#
# when using custom, set maps (and order) in servers.yaml. Key for server must be same as server name as string
playlist: custom
# playlist: linear

# Current phase info
timelimit: 10
jukebox: False
extends: False
num_extends: 2

# LOGGING
logtype: STDOUT # STDOUT, FILE
logfile: /var/www/flask/kacky-eventpage-backend/flask.log # might require absolute path
loglevel: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
logger_name: KKmaptimes

# DATABASE SETTINGS
dbhost: localhost
dbport: 3306
dbname: kacky_backend_rebuild
# dbuser and dbpwd in secrets.yaml need to be set!

# TESTING MODE
testing_mode: 0
testing_compend: 30.01.2050 22:00
