# FLASK/GUNICORN PARAMETERS
port: 5005
# bind_hosts: 127.0.0.1
bind_hosts: 0.0.0.0
workers: 12
threads: 4

# APPLICATION PARAMETERS
install_dir: /eventpage_backend

# META INFO
compstart: 2023-08-17T20:00
compend: 2023-09-17T22:00
eventtype: KR # [KK, KR, KX]
edition: 4 # edition of the eventtype
# playlist parameter can have values ["linear", "custom"]
# - "linear" for [min_mapid, ... max_mapid] on every server
# - "custom" for different maps per server (e. g. colors/difficulties)
#
# when using custom, set maps (and order) in servers.yaml. Key for server must be same as server name as string
playlist: custom
# playlist: linear

# Current phase info
timelimit: 10
jukebox: False
extends: False
num_extends: 2

# LOGGING
logtype: STDOUT # STDOUT, FILE
logfile: /var/www/flask/kacky-eventpage-backend/flask.log # might require absolute path
loglevel: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
logger_name: KKmaptimes

# DATABASE SETTINGS
dbhost: mariadb_serv
dbport: 3306
dbname: kacky_backend_rebuild
# dbuser and dbpwd in secrets.yaml need to be set!

# TESTING MODE
testing_mode: 0
testing_compend: 2050-01-30T22:00
testing_compstart: 2023-01-30T22:00
